### PR TITLE
Peec view modes

### PR DESCRIPTION
**Pull request by cjwest**
Hey @sherakama or @boznik,

These are new view modes for PEEC. Please review.
https://stanfordits.atlassian.net/browse/PEEC-16

### CODE REVIEW

**Comment by sherakama** [comment]
This all looks fine code wise. The only issue I want to raise is about a name. What does an "Image left" look like? I don't think this label is descriptive enough.

**Comment by cjwest** [comment]
@sherakama, 
So this new view mode is a postcard with the image on the left, no wrap. I'm at a loss for a different name. Can you suggest a better name?

**Comment by sherakama** [comment]
How about stanford_4_col_header_left as that is the size and placement of the view mode.

**Comment by cjwest** [comment]
Hey @sherakama,
Given that it can display at multiple spans (4 and the target span is 6 once I remove some padding) , what about:
stanford_header_left ?

**Comment by sherakama** [comment]
If I enabled this feature on a plain vanilla drupal site and did not modify anything what would this view mode look like?

**Comment by cjwest** [comment]
It looks fine to me. See the first "ARPA-E Large Scale Energy Reductions through Sensors, Feedback, and Information Technology" block on
 https://sites.stanford.edu/jsa-peec/

**Comment by sherakama** [comment]
Can you describe the size shape and placement of the image?

**Comment by cjwest** [comment]
stanford_header_150_width_left

**Comment by sherakama** [comment]
Thats what I was fishing for. Lets go with that.
Thanks

**Comment by cjwest** [comment]
👍  🎣

**Comment by cjwest** [comment]
@sherakama,
As you wish!

Also see: https://github.com/SU-SWS/stanford_bean_types/pull/32

**Pull request merged**
