### PR TITLE
Cache yer views

### PR DESCRIPTION
**Pull request by sherakama**
Free performance for everyone!

### CODE REVIEW

**Comment by jbickar** [comment]
I get a broken/missing handler for this View:

```
<   /* Field: Broken/missing handler */
<   $handler->display->display_options['fields']['label']['id'] = 'label';
<   $handler->display->display_options['fields']['label']['table'] = 'bean';
<   $handler->display->display_options['fields']['label']['field'] = 'label';
<   $handler->display->display_options['fields']['label']['relationship'] = 'field_s_image_info_bean';
```

**Comment by sherakama** [comment]
Ok two things,

There was a missing bean relationship that I had removed and this is an admin view so I also removed the caching.  Please have nuther review.

**Comment by jbickar** [comment]
A different broken/missing handler this time, on the `stanford_bulk_fc_image_administration` View:

```
<   /* Field: Content: Title */
<   $handler->display->display_options['fields']['title']['id'] = 'title';
<   $handler->display->display_options['fields']['title']['table'] = 'node';
<   $handler->display->display_options['fields']['title']['field'] = 'title';
<   $handler->display->display_options['fields']['title']['relationship'] = 'field_s_image_info_node';
<   $handler->display->display_options['fields']['title']['hide_empty'] = TRUE;
<   /* Field: Content: Has new content */
<   $handler->display->display_options['fields']['timestamp']['id'] = 'timestamp';
<   $handler->display->display_options['fields']['timestamp']['table'] = 'history';
<   $handler->display->display_options['fields']['timestamp']['field'] = 'timestamp';
<   $handler->display->display_options['fields']['timestamp']['relationship'] = 'field_s_image_info_node';
<   $handler->display->display_options['fields']['timestamp']['label'] = 'New';
<   $handler->display->display_options['fields']['timestamp']['element_label_colon'] = FALSE;
<   /* Field: Content: Published */
<   $handler->display->display_options['fields']['status']['id'] = 'status';
<   $handler->display->display_options['fields']['status']['table'] = 'node';
<   $handler->display->display_options['fields']['status']['field'] = 'status';
<   $handler->display->display_options['fields']['status']['relationship'] = 'field_s_image_info_node';
<   $handler->display->display_options['fields']['status']['not'] = 0;
    /* Field: Field collection item: Caption */
    $handler->display->display_options['fields']['field_s_image_caption']['id'] = 'field_s_image_caption';
    $handler->display->display_options['fields']['field_s_image_credits']['table'] = 'field_data_field_s_image_credits';
    $handler->display->display_options['fields']['field_s_image_credits']['field'] = 'field_s_image_credits';
<   /* Field: Content: Post date */
<   $handler->display->display_options['fields']['created']['id'] = 'created';
<   $handler->display->display_options['fields']['created']['table'] = 'node';
<   $handler->display->display_options['fields']['created']['field'] = 'created';
<   $handler->display->display_options['fields']['created']['relationship'] = 'field_s_image_info_node';
<   $handler->display->display_options['fields']['created']['date_format'] = 'stanford_time';
<   $handler->display->display_options['fields']['created']['second_date_format'] = 'stanford_time';
```

**Comment by sherakama** [comment]
You punking me? Nothing there says its broken.

**Comment by jbickar** [comment]
Are you testing on a JS\* install, or core Stanford?

**Comment by sherakama** [comment]
JSA. Core wont have it as nothing will have the relationship.
Its a cart before the horse issue. With stuff outside our products.

**Comment by jbickar** [comment]
Then the module should declare whatever it needs as a dependency. Or else the View should live elsewhere.

**Comment by sherakama** [comment]
The dependency is to add the field collection field to something. If you don't add the field collection to something then you are not using the module and nothing would show up in the view anyhow. I don't like broken views either but I'm not sure how I can enforce that dependency.

**Comment by jbickar** [comment]
Oh, I see what you're saying. OK, let me test with something that uses it.

**Pull request merged**
